import { useEffect, useMemo, useState } from 'react';
import { useAuth } from './hooks/useAuth';
import { Header } from './components/Header';
import { SignupModal } from './components/SignupModal';
import { approveEscrow, createAndFundEscrow, startEscrow, submitEscrow } from './contracts/localEscrow';

type Project = { id: number; title: string; description: string; visibility: string; status: string; budget_eth: number; recruiter_name?: string; created_at: string };
type Milestone = { id: number; project_id: number; title: string; description: string; amount_eth: number; status: string; developer_name?: string; tx_hash?: string | null };
type Post = { id: number; post_type: string; title: string; content: string; skills: string[]; links: string[]; likes: number; created_at: string; author?: { name: string; role: string; wallet_address: string } };
type AccessRequest = { id: number; status: string; message: string; project?: Project; requester?: { name: string; wallet_address: string } };
type View = 'overview' | 'projects' | 'posts' | 'contracts' | 'profile' | 'connections';
const API = import.meta.env.VITE_API_URL || '/api';

function App() {
  const { isAuthenticated, walletAddress, userProfile, isLoading, error: authError } = useAuth();
  const [showSignupModal, setShowSignupModal] = useState(false);
  const [projects, setProjects] = useState<Project[]>([]);
  const [milestones, setMilestones] = useState<Milestone[]>([]);
  const [posts, setPosts] = useState<Post[]>([]);
  const [accessRequests, setAccessRequests] = useState<AccessRequest[]>([]);
  const [postDraft, setPostDraft] = useState({ title: '', content: '', post_type: 'project_update', skills: '' });
  const [activeView, setActiveView] = useState<View>('overview');
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [showProjectForm, setShowProjectForm] = useState(false);
  const [notice, setNotice] = useState('');
  const [localContractId, setLocalContractId] = useState<string | null>(null);
  const [contractStep, setContractStep] = useState('Ready to fund');
  const [projectForm, setProjectForm] = useState({ title: '', description: '', budget_eth: '0.1', visibility: 'public' });
  const [profileForm, setProfileForm] = useState({ name: '', email: '' });

  useEffect(() => { if (walletAddress && !userProfile && !isLoading) setShowSignupModal(true); }, [walletAddress, userProfile, isLoading]);
  useEffect(() => { fetch(`${API}/projects`).then((r) => r.ok ? r.json() : { projects: [] }).then((data) => setProjects(data.projects || [])).catch(() => setProjects([])); fetch(`${API}/posts`).then((r) => r.ok ? r.json() : { posts: [] }).then((data) => setPosts(data.posts || [])).catch(() => setPosts([])); }, [isAuthenticated]);
  useEffect(() => { if (!walletAddress) return; fetch(`${API}/access-requests?wallet=${walletAddress}`).then((r) => r.ok ? r.json() : { accessRequests: [] }).then((data) => setAccessRequests(data.accessRequests || [])).catch(() => setAccessRequests([])); }, [walletAddress]);
  useEffect(() => { if (!projects.length) return; Promise.all(projects.map((p) => fetch(`${API}/projects/${p.id}/milestones`).then((r) => r.json()).catch(() => ({ milestones: [] })))).then((items) => setMilestones(items.flatMap((item) => item.milestones || []))); }, [projects]);
  useEffect(() => { if (userProfile) setProfileForm({ name: userProfile.name || '', email: userProfile.email || '' }); }, [userProfile]);

  const myProjects = useMemo(() => projects.filter((project) => project.recruiter_name === userProfile?.name), [projects, userProfile]);
  const activeMilestones = milestones.filter((m) => ['active', 'pending', 'submitted'].includes(m.status));

  async function startEscrowDemo() { try { if (!walletAddress) throw new Error('Connect a wallet first.'); const result = await createAndFundEscrow(walletAddress, '1', 'Web3LinkedIn MVP milestone'); setLocalContractId(result.contractId); setContractStep('Funded'); setNotice(`Escrow funded on Hardhat. Contract #${result.contractId}; tx ${result.txHash.slice(0, 10)}...`); } catch (error: any) { setNotice(error?.shortMessage || error?.message || 'Escrow transaction failed.'); } }
  async function runContractAction(action: 'start' | 'submit' | 'approve') { if (!localContractId) return setNotice('Fund a local contract first.'); try { if (action === 'start') await startEscrow(localContractId); if (action === 'submit') await submitEscrow(localContractId, `evidence-${Date.now()}`); if (action === 'approve') await approveEscrow(localContractId); const labels = { start: 'Work started', submit: 'Evidence submitted', approve: 'Milestone approved and paid' }; setContractStep(labels[action]); setNotice(`${labels[action]} on Hardhat.`); } catch (error: any) { setNotice(error?.shortMessage || error?.message || 'Contract action failed.'); } }
  async function createProject(event: React.FormEvent) { event.preventDefault(); if (!userProfile) return; const userResponse = await fetch(`${API}/users/${walletAddress}`); const { user } = await userResponse.json(); const response = await fetch(`${API}/projects`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ recruiter_id: user.id, ...projectForm, budget_eth: Number(projectForm.budget_eth) }) }); if (!response.ok) { setNotice('Only recruiter profiles can publish projects.'); return; } const data = await response.json(); setProjects((current) => [data.project, ...current]); setShowProjectForm(false); setProjectForm({ title: '', description: '', budget_eth: '0.1', visibility: 'public' }); setNotice('Project published successfully.'); }
  async function saveProfile(event: React.FormEvent) { event.preventDefault(); if (!walletAddress) return; const response = await fetch(`${API}/profiles/${walletAddress}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(profileForm) }); setNotice(response.ok ? 'Profile updated.' : 'Profile update failed.'); }
  async function requestAccess(projectId: number) { if (!walletAddress) return setNotice('Connect a wallet first.'); const response = await fetch(`${API}/projects/${projectId}/access-requests`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ wallet: walletAddress, message: 'I would like to review this project and discuss a milestone engagement.' }) }); const data = await response.json(); setNotice(response.ok ? 'Access request recorded for review.' : data.error || 'Access request failed.'); }
  async function requestConnection(toWallet: string, name: string) { if (!walletAddress) return setNotice('Connect a wallet first.'); const response = await fetch(`${API}/connections`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ from_wallet: walletAddress, to_wallet: toWallet }) }); setNotice(response.ok ? `Connection request sent to ${name}.` : 'Connection request failed.'); }
  async function publishPost(event: React.FormEvent) { event.preventDefault(); if (!walletAddress || !postDraft.title.trim() || !postDraft.content.trim()) return; const response = await fetch(`${API}/posts`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ wallet: walletAddress, ...postDraft, skills: postDraft.skills.split(',').map((item) => item.trim()).filter(Boolean) }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error || 'Only student profiles can publish showcase updates.'); setPosts((current) => [data.post, ...current]); setPostDraft({ title: '', content: '', post_type: 'project_update', skills: '' }); setNotice('Showcase update published.'); }
  async function reviewRequest(id: number, status: 'approved' | 'rejected') { if (!walletAddress) return; const response = await fetch(`${API}/access-requests/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ wallet: walletAddress, status }) }); const data = await response.json(); if (response.ok) { setAccessRequests((current) => current.map((item) => item.id === id ? { ...item, status } : item)); setNotice(`Request ${status}.`); } else setNotice(data.error || 'Unable to review request.'); }
  async function likePost(id: number) { const response = await fetch(`${API}/posts/${id}/like`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ wallet: walletAddress }) }); if (response.ok) setPosts((current) => current.map((post) => post.id === id ? { ...post, likes: post.likes + 1 } : post)); }

  if (isLoading) return <div className="loading-screen"><div className="mark">W</div><p>Preparing your workspace</p></div>;
  if (!isAuthenticated) return <div className="app-shell"><Header /><main className="landing-main"><section className="hero-section"><div className="eyebrow">THE PROFESSIONAL LAYER FOR WEB3</div><h1>Work you can <span>verify.</span><br />People you can trust.</h1><p className="hero-copy">A wallet-native professional network for discovering talent, showcasing real work, and completing projects with milestone-protected payments.</p><div className="hero-actions"><button className="primary-button" onClick={() => document.querySelector<HTMLButtonElement>('.connect-button')?.click()}>Connect wallet <span>→</span></button><span className="quiet-note">No gas required to create your profile</span></div></section><section className="signal-grid"><div className="signal-card"><span className="signal-index">01</span><strong>Own your identity</strong><p>Your profile is anchored to a wallet you control.</p></div><div className="signal-card"><span className="signal-index">02</span><strong>Show real work</strong><p>Projects, proof and reputation in one place.</p></div><div className="signal-card"><span className="signal-index">03</span><strong>Get paid fairly</strong><p>Milestones keep both sides accountable.</p></div></section></main><SignupModal isOpen={showSignupModal} onClose={() => setShowSignupModal(false)} />{authError && <div className="toast-error">{authError}</div>}</div>;

  return <div className="app-shell"><Header /><main className="workspace"><aside className="sidebar"><div className="side-label">WORKSPACE</div>{(['overview', 'projects', 'posts', 'contracts', 'profile', 'connections'] as View[]).map((view) => <button key={view} className={`side-link ${activeView === view ? 'active' : ''}`} onClick={() => { setActiveView(view); setSelectedProject(null); }}><span className="side-dot" />{view[0].toUpperCase() + view.slice(1)}{view === 'contracts' && activeMilestones.length > 0 && <small>{activeMilestones.length}</small>}</button>)}<div className="side-footer"><span className="status-dot" />Hardhat local</div></aside><section className="content"><div className="content-top"><div><div className="eyebrow">{userProfile?.role === 'recruiter' ? 'RECRUITER WORKSPACE' : 'DEVELOPER WORKSPACE'}</div><h1>{selectedProject ? selectedProject.title : activeView === 'overview' ? `Good to see you, ${userProfile?.name?.split(' ')[0]}.` : activeView[0].toUpperCase() + activeView.slice(1)}</h1><p className="muted">{selectedProject ? 'Project overview and access path.' : activeView === 'overview' ? 'Your professional graph, at a glance.' : 'Keep the important work moving.'}</p></div>{userProfile?.role === 'recruiter' && (activeView === 'projects' || activeView === 'overview') && <button className="primary-button compact" onClick={() => setShowProjectForm(true)}>+ Publish project</button>}</div>{notice && <div className="notice">{notice}<button onClick={() => setNotice('')}>×</button></div>}
      {selectedProject ? <ProjectDetail project={selectedProject} onBack={() => setSelectedProject(null)} onRequest={() => requestAccess(selectedProject.id)} /> : activeView === 'overview' ? <Overview projects={projects} activeMilestones={activeMilestones} trustScore={userProfile?.trustScore ?? 0} requests={accessRequests} role={userProfile?.role} onReview={reviewRequest} onProject={(p) => setSelectedProject(p)} onViewProjects={() => setActiveView('projects')} /> : activeView === 'projects' ? <ProjectsView projects={projects} myProjects={myProjects} role={userProfile?.role} onProject={(p) => setSelectedProject(p)} onNew={() => setShowProjectForm(true)} /> : activeView === 'posts' ? <PostsView posts={posts} role={userProfile?.role} draft={postDraft} setDraft={setPostDraft} onPublish={publishPost} onLike={likePost} /> : activeView === 'contracts' ? <ContractsView milestones={milestones} role={userProfile?.role} localContractId={localContractId} contractStep={contractStep} onFund={startEscrowDemo} onAction={runContractAction} /> : activeView === 'profile' ? <ProfileView profile={userProfile} walletAddress={walletAddress} form={profileForm} setForm={setProfileForm} onSave={saveProfile} /> : <ConnectionsView walletAddress={walletAddress} onConnect={requestConnection} />}
    </section></main><SignupModal isOpen={showSignupModal} onClose={() => setShowSignupModal(false)} />{showProjectForm && <ProjectModal form={projectForm} setForm={setProjectForm} onClose={() => setShowProjectForm(false)} onSubmit={createProject} />}</div>;
}
function Overview({ projects, activeMilestones, trustScore, requests, role, onReview, onProject, onViewProjects }: { projects: Project[]; activeMilestones: Milestone[]; trustScore: number; requests: AccessRequest[]; role?: string; onReview: (id: number, status: 'approved' | 'rejected') => void; onProject: (p: Project) => void; onViewProjects: () => void }) { return <><div className="stat-row"><div className="stat-card"><span>PROFILE STATUS</span><strong>Verified</strong><em>Wallet ownership confirmed</em></div><div className="stat-card"><span>PROJECTS</span><strong>{projects.length}</strong><em>Public opportunities</em></div><div className="stat-card"><span>ACTIVE WORK</span><strong>{activeMilestones.length}</strong><em>Milestones in motion</em></div><div className="stat-card"><span>TRUST SCORE</span><strong>{trustScore}</strong><em>Built through completed work</em></div></div><div className="section-grid"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">DISCOVER</span><h2>Open projects</h2></div><button className="text-button" onClick={onViewProjects}>View all →</button></div>{projects.length ? projects.slice(0, 3).map((project) => <ProjectRow key={project.id} project={project} onClick={() => onProject(project)} />) : <EmptyState text="No projects published yet." />}</div><div className="panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">ON-CHAIN ACTIVITY</span><h2>Recent signals</h2></div></div><div className="activity-item"><span className="activity-icon">↗</span><div><strong>Wallet connected</strong><p>Identity established on Hardhat</p></div><time>Now</time></div><div className="activity-item"><span className="activity-icon">◇</span><div><strong>Reputation initialized</strong><p>Score starts at zero by design</p></div><time>Today</time></div></div></div>{role === 'recruiter' && <div className="panel full-panel request-inbox"><div className="panel-heading"><div><span className="eyebrow">OWNER INBOX</span><h2>Access requests</h2></div></div>{requests.length ? requests.map((request) => <div className="request-row" key={request.id}><div><strong>{request.requester?.name || 'Builder'}</strong><p>{request.project?.title || 'Project'} · {request.message}</p></div><span className={`status-pill ${request.status}`}>{request.status}</span>{request.status === 'pending' && <div className="request-actions"><button className="outline-button" onClick={() => onReview(request.id, 'rejected')}>Decline</button><button className="primary-button compact" onClick={() => onReview(request.id, 'approved')}>Approve</button></div>}</div>) : <EmptyState text="No project access requests yet." />}</div>}</>; }
function PostsView({ posts, role, draft, setDraft, onPublish, onLike }: { posts: Post[]; role?: string; draft: { title: string; content: string; post_type: string; skills: string }; setDraft: (value: { title: string; content: string; post_type: string; skills: string }) => void; onPublish: (event: React.FormEvent) => void; onLike: (id: number) => void }) { return <div className="posts-layout"><div className="panel full-panel"><div className="panel-heading"><div><span className="eyebrow">STUDENT SIGNALS</span><h2>Build in public</h2></div></div>{role === 'developer' ? <form className="post-composer" onSubmit={onPublish}><select value={draft.post_type} onChange={(event) => setDraft({ ...draft, post_type: event.target.value })}><option value="project_update">Project update</option><option value="case_study">Case study</option><option value="looking_for_work">Looking for work</option><option value="learning_log">Learning log</option></select><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Update title" maxLength={100} /><textarea value={draft.content} onChange={(event) => setDraft({ ...draft, content: event.target.value })} placeholder="Describe the work, proof, outcome, or opportunity..." maxLength={1000} /><input value={draft.skills} onChange={(event) => setDraft({ ...draft, skills: event.target.value })} placeholder="Skills, comma separated" /><div><span>{draft.content.length}/1000</span><button className="primary-button compact" type="submit">Publish post →</button></div></form> : <div className="student-note">Student posts are published by developer profiles. Browse the feed and connect with builders.</div>}{posts.map((post) => <article className="post-card" key={post.id}><div className="post-author"><div className="avatar small">{post.author?.name?.slice(0, 1) || 'W'}</div><div><strong>{post.author?.name || 'Web3 builder'}</strong><p>{post.author?.role || 'developer'} · {new Date(post.created_at).toLocaleDateString()}</p></div></div><span className="status-pill">{post.post_type?.split('_').join(' ')}</span><h3 className="post-title">{post.title || 'Showcase update'}</h3><p className="post-content">{post.content}</p>{post.skills?.length > 0 && <div className="post-skills">{post.skills.map((skill) => <span key={skill}>{skill}</span>)}</div>}<button className="like-button" onClick={() => onLike(post.id)}>Like · {post.likes}</button></article>)}{!posts.length && <EmptyState text="No student posts yet. Be the first builder to share a signal." />}</div></div>; }
function ProjectsView({ projects, myProjects, role, onProject, onNew }: { projects: Project[]; myProjects: Project[]; role?: string; onProject: (p: Project) => void; onNew: () => void }) { return <div className="panel full-panel"><div className="panel-heading"><div><span className="eyebrow">PROJECT DIRECTORY</span><h2>{role === 'recruiter' ? 'Your opportunities' : 'Work looking for talent'}</h2></div>{role === 'recruiter' && <button className="primary-button compact" onClick={onNew}>+ New project</button>}</div>{(role === 'recruiter' ? myProjects : projects).length ? (role === 'recruiter' ? myProjects : projects).map((project) => <ProjectRow key={project.id} project={project} onClick={() => onProject(project)} />) : <EmptyState text="The directory is empty. Publish the first project." />}</div>; }
function ProjectDetail({ project, onBack, onRequest }: { project: Project; onBack: () => void; onRequest: () => void }) { return <div className="detail-layout"><div className="panel full-panel"><button className="text-button" onClick={onBack}>← Back to projects</button><div className="detail-heading"><span className="project-mark large">{project.title.slice(0, 1)}</span><div><span className="eyebrow">PROJECT #{project.id} · {project.visibility}</span><h2>{project.title}</h2><p>{project.description}</p></div></div><div className="detail-grid"><div><span className="eyebrow">BUDGET</span><strong className="detail-value">{project.budget_eth} ETH</strong></div><div><span className="eyebrow">STATUS</span><strong className="detail-value">{project.status}</strong></div><div><span className="eyebrow">POSTED</span><strong className="detail-value">{new Date(project.created_at).toLocaleDateString()}</strong></div></div><button className="primary-button" onClick={onRequest}>Request project access →</button></div><div className="panel"><span className="eyebrow">ACCESS MODEL</span><h2>Start with a verified signal.</h2><p className="body-copy">Public project summaries stay visible. Detailed files and private repository access can be shared after the owner reviews your request.</p><div className="access-step"><span>01</span><p><strong>Request</strong><br />Send your wallet-backed interest.</p></div><div className="access-step"><span>02</span><p><strong>Review</strong><br />The project owner approves access.</p></div><div className="access-step"><span>03</span><p><strong>Build</strong><br />Agree on milestones and escrow.</p></div></div></div>; }
function ContractsView({ milestones, role, localContractId, contractStep, onFund, onAction }: { milestones: Milestone[]; role?: string; localContractId: string | null; contractStep: string; onFund: () => void; onAction: (a: 'start' | 'submit' | 'approve') => void }) { return <div className="panel full-panel"><div className="panel-heading"><div><span className="eyebrow">MILESTONE ESCROW</span><h2>Your contracts</h2></div></div>{milestones.map((m) => <div className="contract-row" key={m.id}><div className="contract-status"><span className={`status-pill ${m.status}`}>{m.status}</span><strong>{m.title}</strong><p>{m.description}</p></div><div className="contract-amount"><strong>{m.amount_eth} ETH</strong><span>Milestone amount</span></div></div>)}<div className="local-contract-card"><span className="eyebrow">LOCAL HARDHAT DEMO</span><h3>{localContractId ? `Contract #${localContractId}` : 'No local contract yet'}</h3><p>{contractStep}. Demonstrate the full payment lifecycle with the deployed local contract.</p><div className="contract-actions">{role === 'recruiter' && <button className="primary-button compact" onClick={onFund}>Create & fund</button>}{localContractId && role === 'developer' && <><button className="outline-button" onClick={() => onAction('start')}>Start work</button><button className="outline-button" onClick={() => onAction('submit')}>Submit evidence</button></>}{localContractId && role === 'recruiter' && <button className="primary-button compact" onClick={() => onAction('approve')}>Approve & release</button>}</div></div></div>; }
function ProfileView({ profile, walletAddress, form, setForm, onSave }: { profile: any; walletAddress: string | null; form: { name: string; email: string }; setForm: (f: { name: string; email: string }) => void; onSave: (e: React.FormEvent) => void }) { return <div className="profile-layout"><div className="profile-card"><div className="avatar">{profile?.name?.slice(0, 1) || 'W'}</div><span className="eyebrow">{profile?.role}</span><h2>{profile?.name}</h2><p className="muted">{profile?.email}</p><div className="wallet-line">{walletAddress?.slice(0, 10)}...{walletAddress?.slice(-8)}</div></div><form className="panel profile-editor" onSubmit={onSave}><span className="eyebrow">EDIT PROFILE</span><h2>Keep your signal current.</h2><label>Display name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label><button className="primary-button compact">Save profile →</button></form></div>; }
function ConnectionsView({ walletAddress, onConnect }: { walletAddress: string | null; onConnect: (wallet: string, name: string) => void }) { const people = [{ name: 'Alice Recruiter', role: 'Product recruiter', wallet: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', score: 92 }, { name: 'Bob Developer', role: 'Protocol designer', wallet: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC', score: 86 }]; return <div className="panel full-panel"><div className="panel-heading"><div><span className="eyebrow">PROFESSIONAL GRAPH</span><h2>Connections</h2></div></div><p className="body-copy">Send a wallet-backed professional connection request. Requests are persisted by the local API.</p>{people.filter((person) => person.wallet.toLowerCase() !== walletAddress?.toLowerCase()).map((person) => <div className="connection-row" key={person.name}><div className="avatar small">{person.name[0]}</div><div><strong>{person.name}</strong><p>{person.role}</p></div><span className="connection-score">{person.score} trust</span><button className="outline-button" onClick={() => onConnect(person.wallet, person.name)}>Connect</button></div>)}</div>; }
function ProjectRow({ project, onClick }: { project: Project; onClick: () => void }) { return <button className="project-row" onClick={onClick}><span className="project-mark">{project.title.slice(0, 1)}</span><span className="project-copy"><strong>{project.title}</strong><p>{project.description}</p></span><span className="project-meta"><b>{project.budget_eth} ETH</b><small>{project.status}</small></span><span className="arrow">→</span></button>; }
function EmptyState({ text }: { text: string }) { return <div className="empty-state"><span>◇</span><p>{text}</p></div>; }
function ProjectModal({ form, setForm, onClose, onSubmit }: { form: any; setForm: (f: any) => void; onClose: () => void; onSubmit: (e: React.FormEvent) => void }) { return <div className="modal-backdrop"><form className="project-form" onSubmit={onSubmit}><button type="button" className="close-button" onClick={onClose}>×</button><span className="eyebrow">NEW OPPORTUNITY</span><h2>Publish a project</h2><p className="muted">Give the right builder enough signal to start a conversation.</p><label>Project title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Build a token-gated portfolio" /></label><label>Description<textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="What needs to be built?" /></label><div className="form-grid"><label>Budget (ETH)<input type="number" min="0" step="0.01" value={form.budget_eth} onChange={(e) => setForm({ ...form, budget_eth: e.target.value })} /></label><label>Visibility<select value={form.visibility} onChange={(e) => setForm({ ...form, visibility: e.target.value })}><option value="public">Public</option><option value="private">Private</option></select></label></div><button className="primary-button" type="submit">Publish project →</button></form></div>; }
export default App;
